# Use the httpd-parent image as base
#FROM quay.io/redhattraining/httpd-parent
FROM localhost/parent

RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf && \
    sed -i "s/#ServerName www.exampl.com:80/ServerName 0.0.0.0:8080/g" /etc/httpd/conf/httpd.conf
